name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Dependencies
      run: |
        npm ci
        cd apps/frontend && npm ci
        cd ../backend && npm ci
        
    - name: Build
      run: |
        npm run build
        cd apps/frontend && npm run build
        cd ../backend && npm run build
        
    - name: Test
      run: |
        npm test
        cd apps/frontend && npm test
        cd ../backend && npm test
        
    - name: Lint
      run: |
        npm run lint
        cd apps/frontend && npm run lint
        cd ../backend && npm run lint 